### ISSUE TITLE
How to adapt this project to my db?

### ISSUE THREAD

**Issue by MarceloAritaAdvisia** [ShayanTalaei/CHESS#14]
Hello, Shayan! 

First of all, thank you for the incredible work on CHESS—I've really appreciated exploring it, and I’m eager to adapt it to my setup.

I'm using an Azure SQL Server database with a single database and five tables. My goal is to make this adaptation as straightforward as possible, ideally with minimal modifications to the existing codebase.

Could you suggest the simplest approach to integrate my database with CHESS? If there are specific files or configurations that I should focus on or modify, I'd appreciate the guidance. Thanks again for sharing this great project!

**Comment by ShayanTalaei** [comment]
Hi Marcelo,

Thanks for reaching out! I'm glad to hear you're interested in adapting CHESS to your setup.

Fortunately, our code is designed to be modular and can be easily adapted to different database management systems, including Azure SQL Server. The key area you'll need to focus on is the `database_utils` directory. This is where we define all interactions with the database, such as SQL execution, parsing, and schema processing.

To integrate your Azure SQL Server database with CHESS, you can modify or extend the functions within the `database_utils` directory to be compatible with Azure SQL Server. Ensure that the function interfaces remain consistent so that the rest of the codebase can interact seamlessly with your database.

I hope this helps! If you have any questions or need further assistance, please feel free to reach out.
