### ISSUE TITLE
What's the full time to execute one quesiton roughly?

### ISSUE THREAD

**Issue by demouo** [ShayanTalaei/CHESS#22]
Hi! It's a great work. I have used CHESS to solve some question in the finance field and it is so helpful. And my estimated running time of one question about 2～3 tables is about 3 ~ 5min. I am a beginner sry. Is it ok for a natural question?

**Comment by ShayanTalaei** [comment]
Hi! 
Thanks for your interest in our work, and happy to hear that it was helpful for your usecase.

Our framework consists of a preprocessing phase and an inference phase per query. The first one might take some time, but it's a one-time cost in the preprocessing step. However, the per-query inference is relatively fast and should be under a minute if you're using OpenAI/Gemini APIs. Since it's a bit hard to identify the source of the latency in an end-to-end fashion, I'd recommend enabling the `info` logging mode and see what step is becoming the bottleneck. 

I hope this has helped you! If you still have an issue with the system's runtime, feel free to reach out with the step that causes the latency so we can resolve it.
