### ISSUE TITLE
Error: `call_agent` 

### ISSUE THREAD

**Issue by cingtiye** [ShayanTalaei/CHESS#23]
https://github.com/ShayanTalaei/CHESS/blob/main/src/workflow/agents/agent.py

The function should call the `system_state` and `self.chat_history` as input, but `system_state` is not be called.

```python
  def call_agent(self, system_state: SystemState) -> SystemState:
      """
      Call the agent with the given system state.
      """
      
      messages = ""
      for chat in self.chat_history:
          role = chat["role"]
          content = chat["content"]
          messages += f"<{role}>\n{content}\n</{role}>\n"
      messages += f"<agent>\n"
      
      llm_chain = get_llm_chain(engine_name=self.config["engine"], temperature=0)
      response = call_engine(message=messages, engine=llm_chain)
      return response
````

**Comment by ShayanTalaei** [comment]
Thanks for your question! In our implementation, we add the information that the agent needs to observe, the state of the tool results upon execution, to the chat history. Moreover, the SystemState will be used when an agent calls a tool as its argument.

**Comment by mahmoudtarek97** [comment]
@cingtiye Hi, I faced the same problem, did you figure it out? if so can you please share your thoughts? and thanks in advance.

@ShayanTalaei First of all, thank you for this great work. 
Our question is simply that why passing `system_state` to `call_agent` while it is not used in the scope/body of that function (We know that `system_state` is used in `call_tool`)?

Also the definition of the `call_agent` says that it will return a `SystemState` object but what it actually returns is a **String** response

Another problem that faced me when I used smaller models like `Qwen/Qwen2.5-1.5B-Instruct` is that the model doesn't consider to respond with a tool to use constrained by the prompt that asks to do so.

For example, the following prompt

`<system>\nHuman: You are the Information Retriever agent, in a team of agents trying to collaboratively transform a natural language question into a SQL query.\nYour task is to (\'retrieve the most important entities and context relevant to the keywords of the question, through \', \'extracting keywords, retrieving entities, and retrieving context\').\n\nYou have access to the following tools. You need to call them in the correct order to complete your task.\n\n<tools>\n1. extract_keywords\n2. retrieve_entity\n3. retrieve_context\n\n</tools>\n\nYou will be given a system state, which contains the current state of the workflow.\n\nPlease identify the next tool you need to call in enclosed in <tool_call> tags.\n\nYou will then be given the result of the tool call, and the new system state.\n\nContinue to identify the next tool you need to call until you have completed your task. When you are done, just return "DONE".\n\n\n</system>\n<agent>\n`

if you pass it to chatgpt it will respond with
`<tool_call> extract_keywords </tool_call>` which is as the next functions expect.

but Qwen/Qwen2.5-1.5B-Instruct gives a generic response like "I understand, please give me the system state and the natural language question bla bla bla ..."

the problem is, the next step of CHESS's agentic code is to parse the response string (making the assumption that the model will follow the rules and will respond according to the prompt) and get the next tool to use as a string also. 
`tool_name = self.get_next_tool_name(response)`
`tool_name = response.split("<tool_call>")[1].split("</tool_call>")[0].strip()`

this puts the flow of the new version of the code (the agentic one not the old pipeline one) under the mercy of the agent's reasoning capability/instruction following.

I know that your intention is to delegate the responsibility of choosing what to do next on the agent itself, injecting some sort of self-reflection/awareness to the code, but that will not work with smaller models 

accordingly, this requires to adjust the prompts with smaller models forcing it to generate valid responses for the next code steps.

**Comment by cingtiye** [comment]
> @cingtiye Hi, I faced the same problem, did you figure it out? if so can you please share your thoughts? and thanks in advance.
> 
> @ShayanTalaei First of all, thank you for this great work. Our question is simply that why passing `system_state` to `call_agent` while it is not used in the scope/body of that function (We know that `system_state` is used in `call_tool`)?
> 
> Also the definition of the `call_agent` says that it will return a `SystemState` object but what it actually returns is a **String** response
> 
> Another problem that faced me when I used smaller models like `Qwen/Qwen2.5-1.5B-Instruct` is that the model doesn't consider to respond with a tool to use constrained by the prompt that asks to do so.
> 
> For example, the following prompt
> 
> `<system>\nHuman: You are the Information Retriever agent, in a team of agents trying to collaboratively transform a natural language question into a SQL query.\nYour task is to (\'retrieve the most important entities and context relevant to the keywords of the question, through \', \'extracting keywords, retrieving entities, and retrieving context\').\n\nYou have access to the following tools. You need to call them in the correct order to complete your task.\n\n<tools>\n1. extract_keywords\n2. retrieve_entity\n3. retrieve_context\n\n</tools>\n\nYou will be given a system state, which contains the current state of the workflow.\n\nPlease identify the next tool you need to call in enclosed in <tool_call> tags.\n\nYou will then be given the result of the tool call, and the new system state.\n\nContinue to identify the next tool you need to call until you have completed your task. When you are done, just return "DONE".\n\n\n</system>\n<agent>\n`
> 
> if you pass it to chatgpt it will respond with `<tool_call> extract_keywords </tool_call>` which is as the next functions expect.
> 
> but Qwen/Qwen2.5-1.5B-Instruct gives a generic response like "I understand, please give me the system state and the natural language question bla bla bla ..."
> 
> the problem is, the next step of CHESS's agentic code is to parse the response string (making the assumption that the model will follow the rules and will respond according to the prompt) and get the next tool to use as a string also. `tool_name = self.get_next_tool_name(response)` `tool_name = response.split("<tool_call>")[1].split("</tool_call>")[0].strip()`
> 
> this puts the flow of the new version of the code (the agentic one not the old pipeline one) under the mercy of the agent's reasoning capability/instruction following.
> 
> I know that your intention is to delegate the responsibility of choosing what to do next on the agent itself, injecting some sort of self-reflection/awareness to the code, but that will not work with smaller models
> 
> accordingly, this requires to adjust the prompts with smaller models forcing it to generate valid responses for the next code steps.

Hi, I manually added some necessary information in 'system_state' to chat history.
